export const BASE_URL = 'http://localhost:5000';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const FETCH_ALL_COLLECTIONS = 'FETCH_ALL_COLLECTIONS';
export const FETCH_COLLECTION = 'FETCH_COLLECTION';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';